ALTER TABLE CRS.dbo.Admin
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Admin
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Courses
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Courses
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Departments
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Departments
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Majors
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Majors
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Payment
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Payment
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.PaymentMethods
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.PaymentMethods
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Professors
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Professors
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.RegistrationStatus
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.RegistrationStatus
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Roles
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Roles
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Roles
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Roles
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.SemesterRegistration
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.SemesterRegistration
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Students
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Students
ADD CreateDateTime DATETIME

ALTER TABLE CRS.dbo.Users
ADD UUID VARCHAR(255)
ALTER TABLE CRS.dbo.Users
ADD CreateDateTime DATETIME

